version: '3.3'

networks:
  carmentis-network:
    driver: bridge

services:
  caddy:
    image: caddy:2
    container_name: carmentis-caddy
    networks:
      - carmentis-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

  operator-db:
    container_name: carmentis-operator-db
    image: postgres:15
    networks:
      - carmentis-network
    volumes:
      - ./operator-storage/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  operator-back:
    depends_on:
      - operator-db
    container_name: carmentis-operator-back
    image: ghcr.io/carmentis/operator/back:stable
    networks:
      - carmentis-network
    restart: always
    volumes:
      - ./operator-config.toml:/app/config.toml
      - ./operator-storage:/operator

  operator-front:
    container_name: carmentis-operator-front
    depends_on:
      - operator-back
    environment:
      - OPERATOR_URL=${OPERATOR_URL}
      - PORT=3000
    image: ghcr.io/carmentis/operator/front:stable
    networks:
      - carmentis-network
    restart: always

volumes:
  caddy_data:
  caddy_config:
