
networks:
  carmentis-network:
    driver: bridge

services:
  caddy:
    image: caddy:2
    container_name: carmentis-caddy
    networks:
      - carmentis-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

  operator:
    container_name: carmentis-operator
    image: ghcr.io/carmentis/operator
    networks:
      - carmentis-network
    restart: always
    volumes:
      - ./operator:/app/operator


volumes:
  caddy_data:
  caddy_config:
